version: "3.6"
services:
  iris:
    build: .
    container_name: iris-history-monitor
    restart: always
    command: --check-caps false
    ports:
      - 51773
      - ${IRIS_PORT}:52773
      - 53773
    volumes:
      - ./src/csp:/opt/irisapp/csp
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/iris/app
